app1/urls.py
from app1.views import *
from django.urls import path

app_name='virat kohli'

urlpatterns=[
    path('template1/',template1,name='template1'),
    path('template2/',template2,name='template2'),
    
]

app2/urls.py
from app2.views import *
from django.urls import path

app_name='Ms_Dhoni'

urlpatterns=[
    path('temaplte1',template1,name='temaplte1'),
    path('template2/',template2,name='template2'),
]

project11/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.

def template1(request):
    return render(request,'template1.html')

def template2(request):
    return render(request,'template2.html')

app2/views.py
from django.shortcuts import render

# Create your views here.

def template1(request):
    return render(request,'template1.html')

def template2(request):
    return render(request,'template2.html')

templates/template1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
        a
        {
            color: greenyellow;
            border: 2px dotted green;
            border-radius: 25px;
        }
        a:hover
        {
            color: blue
        }
    </style>
</head>
<body>
    <CENTER>
        <h1>VIRAT KOHLI</h1>
        <h1>International Hundreds:80</h1>
        <a href="{% url 'Ms_Dhoni:template2' %}"><h1>click here to visit template2</h1></a>
    </CENTER>
    
</body>
</html>

templates/template2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>MS DHONI</h1>
        <a href="{% url 'virat kohli:template1' %}"><h1>click here to visit template1</h1></a>
    </center>
</body>
</html>